export const defaultHomepageSettings = {
  heroEyebrow: "Trusted ecommerce storefront",
  heroTitle: "Shop premium essentials from a store built for modern customers.",
  heroSubtitle: "Discover curated products, clear pricing, fast checkout, and a shopping experience designed for trust from the first click.",
  heroImage: "https://images.unsplash.com/photo-1607082350899-7e105aa886ae?auto=format&fit=crop&w=1800&q=85",
  primaryButtonLabel: "Shop collection",
  primaryButtonHref: "/products",
  secondaryButtonLabel: "Browse categories",
  secondaryButtonHref: "/categories",
  categoryEyebrow: "Shop by category",
  categoryTitle: "Find the right products faster",
  categoryDescription: "Organized storefront categories help shoppers move from discovery to checkout without friction.",
  featuredEyebrow: "Featured products",
  featuredTitle: "Customer-ready products with real shopping actions",
  featuredDescription: "Every product card includes image, price, rating, stock signal, badge support, and add-to-cart behavior.",
  benefitsEyebrow: "Why customers buy",
  benefitsTitle: "Built for trust, clarity, and repeat orders",
  benefitsDescription: "A polished ecommerce homepage should guide shoppers, answer objections, and make the next step obvious.",
  promoEyebrow: "Seasonal offer",
  promoTitle: "Give shoppers a clear reason to buy today.",
  promoDescription: "Use this campaign space for discounts, bundles, free shipping thresholds, product launches, or limited collections.",
  promoImage: "",
  promoButtonLabel: "Shop the offer",
  promoButtonHref: "/products",
  bestSellersEyebrow: "Best sellers",
  bestSellersTitle: "Products shoppers are most likely to explore",
  bestSellersDescription: "Highlight proven items, sale products, or manually curated recommendations to increase conversion.",
  videoGalleryEnabled: false,
  videoGalleryTitle: "Video Gallery",
  videoGalleryDescription: "",
  videoGalleryItems: [],
  posterGalleryEnabled: false,
  posterGalleryTitle: "Poster Gallery",
  posterGalleryDescription: "",
  posterGalleryItems: [],
  testimonialsEyebrow: "Customer proof",
  testimonialsTitle: "A store experience that feels dependable",
  testimonialsDescription: "Use reviews to reinforce trust before shoppers reach checkout.",
  testimonials: [
    {
      name: "Nadia Rahman",
      role: "Boutique customer",
      quote: "The products were easy to browse, the checkout felt clear, and the delivery updates made the order feel reliable.",
      rating: 5,
      image: "",
    },
    {
      name: "Arif Hossain",
      role: "Repeat shopper",
      quote: "The store feels organized and trustworthy. I can find categories fast and compare products without extra noise.",
      rating: 5,
      image: "",
    },
    {
      name: "Maya Chowdhury",
      role: "Small business buyer",
      quote: "The product cards show the details I need immediately: price, rating, stock, and a direct add-to-cart action.",
      rating: 5,
      image: "",
    },
  ],
  newsletterEyebrow: "Member offers",
  newsletterTitle: "Get new arrivals and private offers first",
  newsletterDescription: "Join the store list for product drops, seasonal campaigns, and curated shopping ideas.",
  newsletterButtonLabel: "Subscribe",
};
