import { z } from "zod";

const testimonialSchema = z.object({
  name: z.string().min(1),
  role: z.string().nullish(),
  quote: z.string().min(1),
  rating: z.coerce.number().min(1).max(5).default(5),
  image: z.string().nullish(),
});

export const homepageUpdateSchema = z.object({
  heroEyebrow: z.string().min(1),
  heroTitle: z.string().min(1),
  heroSubtitle: z.string().min(1),
  heroImage: z.string().min(1),
  primaryButtonLabel: z.string().min(1),
  primaryButtonHref: z.string().min(1),
  secondaryButtonLabel: z.string().min(1),
  secondaryButtonHref: z.string().min(1),
  categoryEyebrow: z.string().min(1),
  categoryTitle: z.string().min(1),
  categoryDescription: z.string().min(1),
  featuredEyebrow: z.string().min(1),
  featuredTitle: z.string().min(1),
  featuredDescription: z.string().min(1),
  benefitsEyebrow: z.string().min(1),
  benefitsTitle: z.string().min(1),
  benefitsDescription: z.string().min(1),
  promoEyebrow: z.string().min(1),
  promoTitle: z.string().min(1),
  promoDescription: z.string().min(1),
  promoImage: z.string().nullish(),
  promoButtonLabel: z.string().min(1),
  promoButtonHref: z.string().min(1),
  bestSellersEyebrow: z.string().min(1),
  bestSellersTitle: z.string().min(1),
  bestSellersDescription: z.string().min(1),
  testimonialsEyebrow: z.string().min(1),
  testimonialsTitle: z.string().min(1),
  testimonialsDescription: z.string().min(1),
  testimonials: z.array(testimonialSchema).default([]),
  newsletterEyebrow: z.string().min(1),
  newsletterTitle: z.string().min(1),
  newsletterDescription: z.string().min(1),
  newsletterButtonLabel: z.string().min(1),
});
